projects:
  gocbackendv3:
    schemaPath: amplify/backend/api/gocbackendv3/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/Api.tsx
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/Api.tsx
        docsFilePath: src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
